name: Build AndKittyInjector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the build environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip make

      - name: Setup Android NDK
        run: |
          export NDK_VERSION="26.1.10909125"  # Change this if needed
          wget https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME/android-ndk
          rm ndk.zip
          echo "NDK_HOME=$HOME/android-ndk/android-ndk-r${NDK_VERSION}" >> $GITHUB_ENV
          echo "$HOME/android-ndk/android-ndk-r${NDK_VERSION}" >> $GITHUB_PATH

      - name: Build with ndk-build
        run: |
          export NDK_HOME=$HOME/android-ndk/android-ndk-r26.1.10909125  # Ensure the path is correct
          make all

      - name: Upload Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: AndKittyInjector
          path: libs/  # Adjust this based on where your built files are
