name: Build AndKittyInjector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the build environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip make

      - name: Download & Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME/android-ndk
          rm ndk.zip
          echo "NDK_HOME=$HOME/android-ndk/android-ndk-r27c" >> $GITHUB_ENV
          echo "$HOME/android-ndk/android-ndk-r27c" >> $GITHUB_PATH

     

      - name: Build with ndk-build
        run: |
          export NDK_HOME=$HOME/android-ndk/android-ndk-r27c
          $NDK_HOME/ndk-build -j16 -B \
            NDK_PROJECT_PATH=. \
            NDK_APPLICATION_MK=./Application.mk
            

          

      - name: Upload Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: AndKittyInjector
          path: libs/  # Adjust if needed
