name: Build AndKittyInjector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake make git

      - name: Build Project
        run: |
          chmod +x build.sh  # Ensure your build script is executable
          ./build.sh  # Run your build script

      - name: Upload Artifact (Optional)
        uses: actions/upload-artifact@v4  # Fixed version
        with:
          name: AndKittyInjector
          path: build/output/  # Adjust this based on your output path
